#!/bin/bash
cwd=$(pwd)

# Check if the script is running as root
if [ "$EUID" -ne 0 ]; then
    echo "This script requires elevated privileges (root)."
    exec sudo "$0" "$@"
fi

# Copy the file ./streamlit-dockerize to /usr/local/bin
cp streamlit-dockerize /usr/local/bin
